# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'HealthieApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HealthieApp
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'AlamofireImage', '~> 3.5'
  pod 'Koloda'
  pod 'VerticalCardSwiper'
end
